version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:

  build_win:
    build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            docker info
            docker run hello-world:nanoserver-1809

  build_linux:
    docker:
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: "OS fingerprinting - Debian GNU/Linux 10 (buster) x86_64"
          command: |
            uname -a
            cat /etc/issue
            cat /etc/os-release  


workflows:
  commit-parallel-workflow:
    jobs:
      - build_win
      - build_linux
  scheduled-workflow:
    triggers:
      - schedule:        
          # cron: "0,15,30,45 * * * *" # three times every hour, at minutes 0, 15, 30, 45
          cron: "0 01 1 * *" # three times every hour, at minutes 0, 15, 30, 45
          filters:
            branches:
              only: 
              - test
    jobs:
      - build_win
      - build_linux
